DROP DATABASE IF EXISTS burger_db;

CREATE DATABASE burger_db;

DROP TABLE IF EXISTS burgers;

CREATE TABLE burgers (
    id INT(11) NOT NULL AUTO_INCREMENT,
    burger_name VARCHAR(255) NOT NULL,
    devoured BOOLEAN DEFAULT FALSE,
    PRIMARY KEY(id)
);
